beris147/whoami

common/types.js
common/types/leaveRoomRequestType.js
server/src/sockets/handlers/roomHandler.js

When a 'leave-room' message is received. The user should leave their room. Emitting a 'left-room' message in  response.
Solves #11 
Hopefully this works, at least it doesn't break anything.
Proper testing is postponed until we add testing features in the project.

Leave room backend

---

common/types.js
common/types/leaveRoomRequestType.js
server/.babelrc
server/__tests__/room.test.js
server/package-lock.json
server/package.json
server/src/sockets/handlers/roomHandler.js

A simple test to verify that jest is working. 
`npm test`

Jest added to server

---

client/src/App.js
client/src/components/CreateRoom.js
client/src/components/JoinRoom.js
client/src/components/Room.js
client/src/contexts/UserContext.js
client/src/providers/SocketProvider.js
client/src/providers/UserProvider.js
server/src/sockets/handlers/userHandler.js

Dev will be removed after this.

Merge dev to master 

---

server/src/utils/__tests__/userUtils/removeUser.test.js

Solves #35 
**Requirements**
When removing a user:
- Given a user in the user set
- Then remove the user from the set
- Given a user not in the user set
- Then do nothing

Tests for removing a User

---

server/src/utils/__tests__/userUtils/getUserRoom.test.js

Solves #33 
***Requirements***
When getting a user room:
- Given a user whose room appears in the room set
- Then return the room
- Given a user whose room doesn't appear in the room set
- Then return undefined

Tests for getting a user room

---

client/src/components/__mocks__/CustomMemoryRouter.js
client/src/components/__mocks__/MockRouter.js
client/src/components/__tests__/JoinRoom.test.js

after messing the branches
`npm test`

join room tests fixed

---

client/src/components/JoinRoom.js
client/src/components/Room.js
client/src/components/__mocks__/ElementWithProviders.js
client/src/components/__mocks__/MockRouter.js
client/src/components/__tests__/CreateRoom.test.js
client/src/components/__tests__/JoinRoom.test.js
client/src/components/__tests__/Room.test.js
client/src/utils/__mocks__/MockedSocketIO.js

Tests for create room component for issue #22 
To test the sockets behavior I write `MockedSocketIO`, using the `MockedProvider` we can communicate between a fake server and our client.  
`npm test`

Create room tests

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/__tests__/App.test.js
client/src/components/CreateRoom.js
client/src/components/JoinRoom.js
client/src/components/Room.js
client/src/components/__mocks__/ElementWithProviders.js
client/src/components/__mocks__/MockRouter.js
client/src/components/__tests__/CreateRoom.test.js
client/src/components/__tests__/JoinRoom.test.js
client/src/components/__tests__/Room.test.js
client/src/index.js
client/src/providers/SocketProvider.js
client/src/providers/UserProvider.js
client/src/providers/__mocks__/MockedProvider.js
client/src/providers/__tests__/MockedProvider.test.js
client/src/tests/App.test.js
client/src/tests/setupTests.js
client/src/utils/__mocks__/MockedSocketIO.js
client/src/utils/routes.js

removed relative imports

---

server/src/utils/__tests__/userUtils/removeUserFromRoom.test.js

Closes #31 
Update from [this](https://github.com/beris147/whoami/pull/32#issue-620817142) pull request

Tests remove user from room

---

server/src/utils/__tests__/userUtils/removeUserFromRoom.test.js
server/src/utils/roomUtils.js
server/src/utils/userUtils.js

Transfer ownership

---

server/package-lock.json
server/package.json

Continuation of #42 
Also, I delete the lib folder to avoid collisions with pre-build code. closes #58  
`npm test` inside server:
`npm run dev` now runs back end and front end tests:

run tests before running server

---

client/package.json
server/package-lock.json
server/package.json

Continuation of pr #41 
This way we can be sure that everything is working. Closes #22 for the moment, more tests will be added.
`npm start`
If some this fails:

run tests pre-start and pre-build

---

client/package.json
client/src/components/__tests__/Home.test.js
server/package-lock.json
server/package.json

Continuation of pull request #40 
`npm test`
Currently home does nothing special, just check if it renders.

simple home test added

---

client/package.json
client/src/components/__tests__/CreateRoom.test.js
client/src/components/__tests__/Home.test.js
client/src/components/__tests__/JoinRoom.test.js
client/src/components/__tests__/Room.test.js
server/package-lock.json
server/package.json

Cleaner tests, and check redirects on join room and creat room. 
`npm test`

Minor tests fixes

---

server/src/utils/__tests__/userUtils/removeUserById.test.js

Test for `removeUserFromRoom` function continuation of #56 
`npm test`

Remove by id tests

---

client/src/App.js
client/src/components/CreateRoom.js
client/src/components/JoinRoom.js
client/src/components/Room.js

Continuation of #50 
Basic chat with alerts. We emit the message to the rest of the room. 
User 1 writes and sends the message:
User 2 receives the message:
User 2 writes and sends the message:
User 1 receives the message:

basic chat client side with alerts

---

client/src/App.js
client/src/components/CreateRoom.js
client/src/components/JoinRoom.js
client/src/components/Room.js
server/src/sockets/handlers/roomHandler.js
server/src/utils/roomUtils.js

Continuation of #49 
Closes #2 
When a user sends a message, emit it to the rest of the room, except the sender. Tested later on the stack.

Chat back end side

---

client/src/App.js
client/src/components/CreateRoom.js
client/src/components/JoinRoom.js
client/src/components/Room.js
common/types.js
common/types/messageType.js
server/src/sockets/handlers/roomHandler.js
server/src/utils/roomUtils.js

Continuation of #48 
Basic type for message

Message type

---

client/src/App.js
client/src/components/CreateRoom.js
client/src/components/JoinRoom.js
client/src/components/Room.js
common/types.js
common/types/messageType.js
server/src/sockets/handlers/roomHandler.js
server/src/utils/roomUtils.js

Continuation of #47 
During the process of compilation, some warnings are shown.  
Warnings removed, everything is working client-side

react warnings removed

---

.github/workflows/flow.yml
.github/workflows/test.yml
package.json
server/package.json

With this, we can start the GitHub workflow setup. 
`npm test` from root dir

run test from root dir

---

client/src/App.js
client/src/components/PageNotFound.js
client/src/components/__tests__/PageNotFound.test.js

page not found added + page not found testing

---

client/src/components/Chat/Chat.js
client/src/components/CreateRoom.js
client/src/components/JoinRoom.js
client/src/components/__tests__/CreateRoom.test.js
client/src/components/__tests__/JoinRoom.test.js
client/src/utils/__test__/handleOnEnter.test.js
client/src/utils/handleOnEnter.js
client/src/utils/keycodes.js

Continuation of #78 
`npm test`

send message, create and join rooms inputs handles enter event

---

client/src/components/Chat/Chat.js
client/src/components/Chat/MessageList.js
client/src/components/CreateRoom.js
client/src/components/JoinRoom.js
client/src/components/Room.js
client/src/components/__tests__/Chat/Chat.test.js
client/src/components/__tests__/Chat/MessageList.test.js
client/src/components/__tests__/CreateRoom.test.js
client/src/components/__tests__/JoinRoom.test.js
client/src/utils/__test__/handleOnEnter.test.js
client/src/utils/handleOnEnter.js
client/src/utils/keycodes.js
common/types.js
common/types/messageListType.js

basic chat, write, send and see messages on screen

---

server/src/sockets/handlers/roomHandler.js
server/src/utils/userUtils.js

Closes #72 
When a user joins the lobby, it sends a request to the server to get the list of users in the lobby.
This forwards that request to the room owner

Forwards the event to the owner

---

client/src/components/__tests__/lobby/JoinLobby.test.js
client/src/components/__tests__/lobby/ServerAnswersUsersInLobby.test.js
client/src/components/lobby/Lobby.js
server/src/sockets/handlers/roomHandler.js
server/src/utils/userUtils.js

Closes #80 
When the user receives the users in lobby
it emits an event to notify everyone that they joined the lobby

Emit joined

---

client/src/components/Room.js
client/src/components/__tests__/CreateRoom.test.js
client/src/components/__tests__/JoinRoom.test.js
client/src/components/__tests__/lobby/GetUserInLobby.test.js
client/src/components/__tests__/lobby/JoinLobby.test.js
client/src/components/__tests__/lobby/ServerAnswersUsersInLobby.test.js
client/src/components/__tests__/lobby/UserJoins.test.js
client/src/components/lobby/Lobby.js
client/src/components/lobby/PlayButton.js
client/src/components/lobby/ReadyButton.js
client/src/components/lobby/User.js
client/src/components/lobby/UserList.js
client/src/utils/__mocks__/MockedSocketIO.js
common/types.js
common/types/userInLobbyType.js
common/types/userReadyStateType.js
common/types/usersInLobbyCallbackType.js
server/src/sockets/handlers/roomHandler.js
server/src/utils/userUtils.js

Closes #53 
Here's a static component for the lobby.
@danielmnv Can improve the UI while we change the behavior

Adds Lobby component

---

client/src/components/Room.js
client/src/components/__tests__/lobby/ReadyForm.test.js
client/src/components/__tests__/lobby/UserIsReady.test.js
client/src/components/__tests__/lobby/UserJoins.test.js
client/src/components/lobby/Lobby.js
client/src/components/lobby/ReadyButton.js
client/src/components/lobby/ReadyForm.js
client/src/utils/hooks/mounted.js
common/types.js
common/types/userInLobbyType.js
common/types/userIsReadyType.js
server/src/sockets/handlers/roomHandler.js

when a user is ready, emit to the room and update the state of the lobby

---

client/src/components/__tests__/lobby/GetUserInLobby.test.js
client/src/components/__tests__/lobby/ReadyForm.test.js
client/src/components/__tests__/lobby/ServerAnswersUsersInLobby.test.js
client/src/components/__tests__/lobby/UserIsReady.test.js
client/src/components/__tests__/lobby/UserJoins.test.js
client/src/components/lobby/Lobby.js
client/src/components/lobby/ReadyForm.js
client/src/components/lobby/User.js
common/types.js
common/types/userInLobbyType.js
common/types/userIsNotReadyType.js
common/types/userReadyStateType.js
server/src/sockets/handlers/roomHandler.js

update when user is not ready yet

---

client/src/components/Chat/Chat.js
client/src/components/Game.js
client/src/components/__tests__/CreateRoom.test.js
client/src/components/__tests__/JoinRoom.test.js
client/src/components/__tests__/lobby/UserLeaves.test.js
client/src/components/lobby/Lobby.js
client/src/components/lobby/PlayButton.js
client/src/utils/__mocks__/mockedRoomState.js
common/types/roomType.js
server/src/sockets/handlers/gameHandler.js
server/src/utils/__tests__/userUtils/getUserRoom.test.js
server/src/utils/__tests__/userUtils/removeUserById.test.js
server/src/utils/__tests__/userUtils/removeUserFromRoom.test.js
server/src/utils/roomUtils.js

unused properties from room removed

---

client/src/app/__tests__/Lobby/LobbyApp.test.js
client/src/components/__tests__/Lobby/Lobby.test.js
client/src/domain/logic/__tests__/LobbyDomainLogic.test.js
client/src/sockets/__mocks__/Lobby/MockedLobbyServer.js
client/src/sockets/__tests__/Lobby/LobbySocket.test.js
client/src/utils/__mocks__/Lobby/mockedUserListState.js

test for lobby app, socket, domain and component

---

client/src/app/__tests__/Lobby/LobbyApp.test.js
client/src/app/__tests__/RoomApp.test.js
client/src/components/__tests__/Lobby/Lobby.test.js
client/src/domain/logic/__tests__/LobbyDomainLogic.test.js
client/src/domain/logic/__tests__/RoomDomainLogic.test.js
client/src/sockets/__mocks__/Lobby/MockedLobbyServer.js
client/src/sockets/__mocks__/MockedRoomServer.js
client/src/sockets/__tests__/Lobby/LobbySocket.test.js
client/src/sockets/__tests__/RoomSocket.test.js
client/src/utils/__mocks__/Lobby/mockedUserListState.js

basic tests for room app, sockets and domain logic

---

client/src/app/Lobby/LobbyApp.js
client/src/app/RoomApp.js
client/src/app/__tests__/Lobby/LobbyApp.test.js
client/src/app/__tests__/RoomApp.test.js
client/src/components/Room.js
client/src/components/__tests__/Lobby/Lobby.test.js
client/src/components/lobby/Lobby.js
client/src/components/lobby/PlayButton.js
client/src/components/lobby/UserList.js
client/src/contexts/Lobby/LobbyContext.js
client/src/domain/logic/LobbyDomainLogic.js
client/src/domain/logic/__tests__/LobbyDomainLogic.test.js
client/src/domain/logic/__tests__/RoomDomainLogic.test.js
client/src/domain/models/LobbyDomainModels.js
client/src/providers/Lobby/LobbyProvider.js
client/src/sockets/Lobby/LobbySocket.js
client/src/sockets/__mocks__/Lobby/MockedLobbyServer.js
client/src/sockets/__mocks__/MockedRoomServer.js
client/src/sockets/__tests__/Lobby/LobbySocket.test.js
client/src/sockets/__tests__/RoomSocket.test.js
client/src/utils/__mocks__/Lobby/mockedUserListState.js
client/src/utils/hooks/mounted.js

Lobby refactor
